### ISSUE TITLE
Authorization Flow Not Working 

### ISSUE THREAD

**Issue by psy-pri** [psy-pri/spotify-analyser#1]
I'm trying to generate the bearer token to access songs played by the user in the last 24 hours.
However, the authorization flow isn't working despite generating the access token. 

Docs referred - 
<a href="https://developer.spotify.com/documentation/general/guides/authorization/code-flow/">https://developer.spotify.com/documentation/general/guides/authorization/code-flow/</a>

**Comment by ayaan-qadri** [comment]
i wanna help in this.

**Comment by psy-pri** [comment]
@PentW0lf sure, assigned to you!

**Comment by ayaan-qadri** [comment]
Thanks @psy-pri , It would take sometime because I have to read and learn things for system of Authorization for spotify.
