### ISSUE TITLE
Constants file not explained.

### ISSUE THREAD

**Issue by rootkit7628** [psy-pri/spotify-analyser#7]
Can you please explain what the constants file stands for and all the constants variables it should contain?
```py
    from constants import DATABASE_ENGINE
    from constants import TOKEN_URL
    from constants import CLIENT_ID
    from constants import CLIENT_SECRET
    from constants import CHROME_DRIVER_PATH
```
I think it would be better to use `dotenv` file instead.

**Comment by psy-pri** [comment]
Hello @rootkit7628, have added the constant.py file for your reference. You are right about the `dotenv` file, will use it next time!
